#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = -ISFML-2.5.0\\include
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = -LSFML-2.5.0\\lib
LIB = -lsfml-graphics -lsfml-window -lsfml-system
LDFLAGS = 

INC_RELEASE = $(INC) -ISFML-2.5.0\include
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR) -LSFML-2.5.0\lib
LIB_RELEASE = $(LIB) 
LDFLAGS_RELEASE = $(LDFLAGS) -s -static -static-libgcc -static-libstdc++
OBJDIR_RELEASE = 
DEP_RELEASE = 
OUT_RELEASE = galaga.exe

OBJ_RELEASE = $(OBJDIR_RELEASE)\\src\\BezierCurve.o $(OBJDIR_RELEASE)\\src\\main.o $(OBJDIR_RELEASE)\\src\\graphicsWindow.o $(OBJDIR_RELEASE)\\src\\Point.o $(OBJDIR_RELEASE)\\src\\Logger.o $(OBJDIR_RELEASE)\\src\\GameLogic.o $(OBJDIR_RELEASE)\\src\\Fighter.o $(OBJDIR_RELEASE)\\src\\EnemiesRed.o $(OBJDIR_RELEASE)\\src\\EnemiesGreen.o $(OBJDIR_RELEASE)\\src\\Enemies.o $(OBJDIR_RELEASE)\\src\\Bullets.o $(OBJDIR_RELEASE)\\src\\Bonus.o

all: release

clean: clean_release

before_release: 

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\src\\BezierCurve.o: src\\BezierCurve.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\BezierCurve.cpp -o $(OBJDIR_RELEASE)\\src\\BezierCurve.o

$(OBJDIR_RELEASE)\\src\\main.o: src\\main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\main.cpp -o $(OBJDIR_RELEASE)\\src\\main.o

$(OBJDIR_RELEASE)\\src\\graphicsWindow.o: src\\graphicsWindow.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\graphicsWindow.cpp -o $(OBJDIR_RELEASE)\\src\\graphicsWindow.o

$(OBJDIR_RELEASE)\\src\\Point.o: src\\Point.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Point.cpp -o $(OBJDIR_RELEASE)\\src\\Point.o

$(OBJDIR_RELEASE)\\src\\Logger.o: src\\Logger.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Logger.cpp -o $(OBJDIR_RELEASE)\\src\\Logger.o

$(OBJDIR_RELEASE)\\src\\GameLogic.o: src\\GameLogic.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\GameLogic.cpp -o $(OBJDIR_RELEASE)\\src\\GameLogic.o

$(OBJDIR_RELEASE)\\src\\Fighter.o: src\\Fighter.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Fighter.cpp -o $(OBJDIR_RELEASE)\\src\\Fighter.o

$(OBJDIR_RELEASE)\\src\\EnemiesRed.o: src\\EnemiesRed.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\EnemiesRed.cpp -o $(OBJDIR_RELEASE)\\src\\EnemiesRed.o

$(OBJDIR_RELEASE)\\src\\EnemiesGreen.o: src\\EnemiesGreen.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\EnemiesGreen.cpp -o $(OBJDIR_RELEASE)\\src\\EnemiesGreen.o

$(OBJDIR_RELEASE)\\src\\Enemies.o: src\\Enemies.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Enemies.cpp -o $(OBJDIR_RELEASE)\\src\\Enemies.o

$(OBJDIR_RELEASE)\\src\\Bullets.o: src\\Bullets.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Bullets.cpp -o $(OBJDIR_RELEASE)\\src\\Bullets.o

$(OBJDIR_RELEASE)\\src\\Bonus.o: src\\Bonus.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Bonus.cpp -o $(OBJDIR_RELEASE)\\src\\Bonus.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)\\src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

